name: Matrix
on:
  - push
jobs:
  node-version:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 12
          - 14
          - 16
        exclude:
          - os: ubuntu-latest
            node_version: 16
        include:
          - os: ubuntu-latest
            node_version: 14
            node_version_14: true
      max-parallel: 2
      fail-fast: true
    name: Testing node version ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      NODE_VERSION_14: ${{ matrix.node_version_14 }}
    steps:
      - name: Log node version
        run: node -v
      - name: Setup node version ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: |
          node -v
          echo ${NODE_VERSION_14:=NOT_AVAILABLE}
