name: Actions workflow
on:
  - push
jobs:
  run_github_actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Say Hello with actions
        id: greeting
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Hung
      - name: Log Greating Time
        run: echo "${{ steps.greeting.outputs.time }}"
