name: Actions workflow
on:
  push:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - closed

jobs:
  run_github_actions:
    name: Use predefined Github Actions
    runs-on: ubuntu-latest
    steps:
      - name: Inspect ENV
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Say Hello with actions
        id: greeting
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Hung
      - name: Log Greating Time
        run: echo "${{ steps.greeting.outputs.time }}"
