name: CI
on:
  push: # For testing workflow
  pull_request:
    branches:
      - develop
jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Run test
        run: npm test -- --coverage
        env:
          CI: true
