name: CI
on:
  push:
    branches:
      -  "*" # For testing workflow
      - develop

  pull_request:
    branches:
      - develop
jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Run test
        run: npm test -- --coverage
        env:
          CI: true
      - name: Build the project
        if: github.event_name == 'push'
        run: npm run build

      # - name: Install surge globally
      #   if: github.event_name == 'push'
      #   run: npm install -g surge

      - name: Deploy to staging
        if: github.event_name == 'push'
        run: npm run deploy
        env:
          SURGE_LOGIN: nthung.vlvn@gmail.com
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
