name: Container
on:
  - push
jobs:
  node_docker:
    name: Running Node in docker
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api:latest
        ports:
          - 3001:3000
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Post a user
        run: |
          curl -X POST http://localhost:3001/api/user \
            -H 'Content-Type: application/json' \
            -d '{"username": "hello", "address": "Binh Minh"}'
      - name: Get a users
        run: |
          curl -X GET http://localhost:3001/api/users
